language: java
sudo: required
install: true
jdk:
  - oraclejdk8
before_script:
  - chmod +x ./.travis/upload-to-repo.sh
  - sed -i -e 's/\r$//' ./.travis/upload-to-repo.sh
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mkdir ./repository
addons:
  sonarcloud:
    organization: "welle-github" # the key of the org you chose at step #3
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
after_success:
  - mvn -Denv=dev-travis -DperformRelease=true clean deploy
  - ./.travis/upload-to-repo.sh